let n1 = prompt("Digite o primeiro numero: ");
n1 = Number(n1);
let n2 = prompt("Digite o segundo numero: ");
n2 = Number(n2);
alert(`${n1} == ${n2} : ${n1 == n2}`);
alert(`${n1} === ${n2} : ${n1 === n2}`);
alert(`${n1} < ${n2} : ${n1 < n2}`);
alert(`${n1} > ${n2} : ${n1 > n2}`);
alert(`${n1} <= ${n2} : ${n1 <= n2}`);
alert(`${n1} >= ${n2} : ${n1 >= n2}`);
alert(`${n1} != ${n2} : ${n1 != n2}`);
alert(`${n1} !== ${n2} : ${n1 !== n2}`);